### ISSUE TITLE
Transition from Prototype to jQuery (TODO)

### ISSUE THREAD

**Issue by arkon** [MarkUsProject/Markus#1496]
Since the Prototype JavaScript framework is a bit antiquated and slow, we're switching to fully using jQuery (which is now the standard anyway). It should also be noted that we are also using other JS frameworks such as React (by Facebook) for tables.

Of course, vanilla JS is welcome too (which is more efficient than using jQuery for obvious reasons).

Progress/things that still need to be translated:

- [ ] Rails 3 seems to rely on some Prototype code (`prototype-snippet.js`)
- [ ] Inline Prototype code here and there in the HTML files
- [x] RJS files in `app/views/` (which use Prototype) (converted in PR #2309)
- [x] FilterTables (mostly replaced with React.js tables; see issue https://github.com/MarkUsProject/Markus/issues/1696)
- [x] In `app/assets/javascripts/`:
  - [x] `grades_table.js` (converted in PR https://github.com/MarkUsProject/Markus/pull/1639)
  - [x] `manage_graders.js`
  - [x] `manage_groups.js`
  - [x] `users_manager.js`  (deleted in switch to React.js)
- [x] https://github.com/MarkUsProject/Markus/pull/1326 (sort of replaced by React.js stuff)
- [x] https://github.com/MarkUsProject/Markus/pull/1323 (replaced by PR https://github.com/MarkUsProject/Markus/pull/1604)
- [x] https://github.com/MarkUsProject/Markus/pull/1325 (replaced by PR https://github.com/MarkUsProject/Markus/pull/1601)
- [x] Replacing Bluff for drawing graphs with [Chart.js](http://www.chartjs.org/) (done in PR https://github.com/MarkUsProject/Markus/pull/1519)
- [x] calendardateselect (replaced with jQuery UI date/time picker in https://github.com/MarkUsProject/Markus/pull/1511)
- [x] PeriodDeltaChain (uses jQuery as of PR https://github.com/MarkUsProject/Markus/pull/1511)
- [x] SourceCodeGlower, used for annotations (uses jQuery as of PR https://github.com/MarkUsProject/Markus/pull/1517)
- [x] SyntaxHighlighter adapter/mods (uses jQuery as of PR https://github.com/MarkUsProject/Markus/pull/1517)
- [x] The draggable bar in the marks/code view (replaced in PR https://github.com/MarkUsProject/Markus/pull/1529)
- [x] Anything to do with livepipe: (done in PR https://github.com/MarkUsProject/Markus/pull/1588)
  - livepipe/livepipe
  - livepipe/tabs (like in groups/graders lists)
  - livepipe/window (used in various files)

**Comment by david-yz-liu** [comment]
@spring-ryanc One set of small tasks related to this is to finish up the conversion of rjs files to erb files. You should make small PRs for just a few files at a time, so you can make steady progress on this on the side each week.

**Comment by spring-ryanc** [comment]
I removed the marks_graders rjs files as part of PR #2085

**Comment by arkon** [comment]
@spring-ryanc Fantastic! That means only 1 FilterTable remains: https://github.com/MarkUsProject/Markus/blob/master/app/views/submissions/_file_manager_boot.js.erb

**Comment by david-yz-liu** [comment]
@spring-ryanc Note: we have a Toronto student working on that table right now.
