### ISSUE TITLE
Rails 4 outstanding issues

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#1995]
- [x] Two rspec tests fail in rails4 branch #1923
- [x] Can't add annotations to marking view #1920
- [x] PDF annotations don't work #1941
- [ ] scss warnings in server log #1924
- [x] Collect all submissions is broken #1996
